CREATE TABLE auth_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    user_id  BIGINT,
    CONSTRAINT pk_authuser PRIMARY KEY (id)
);

CREATE TABLE todo
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    todo_name VARCHAR(255),
    state     BOOLEAN                                 NOT NULL,
    user_id   BIGINT,
    CONSTRAINT pk_todo PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE auth_user
    ADD CONSTRAINT uc_authuser_user UNIQUE (user_id);

ALTER TABLE auth_user
    ADD CONSTRAINT FK_AUTHUSER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE todo
    ADD CONSTRAINT FK_TODO_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


insert into users(first_name, last_name, email) VALUES
    ('Khang', 'Pham', 'khang@gmail.com'),
    ('Hue', 'Doan', 'hue@gmail.com'),
    ('long', 'nguyen', 'long@gmail.com');



insert into auth_user(username, password, user_id) VALUES
    ('khangpham', '$2a$10$yeUDM.vZKvQHYmHhSWxyTukeKy4oQ04CyV9WEBVRxogywe3xSRvyS',(select users.id from users where email='khang@gmail.com')),
    ('huedoan', '$2a$10$yeUDM.vZKvQHYmHhSWxyTukeKy4oQ04CyV9WEBVRxogywe3xSRvyS',(select users.id from users where email='hue@gmail.com')),
    ('longnguyen', '$2a$10$yeUDM.vZKvQHYmHhSWxyTukeKy4oQ04CyV9WEBVRxogywe3xSRvyS',(select users.id from users where email='long@gmail.com'));
